### ISSUE TITLE
Blockbench model not found

### ISSUE THREAD

**Issue by HastagGuigui** [Manuel-3/figura-vscode-extension#1]
When I open my script file, this warning message pops up, even though there's a .bbmodel file present

![image](https://user-images.githubusercontent.com/47950669/187898360-c5503f58-63de-4a1d-b3f6-d2aa04c437fa.png)
![image](https://user-images.githubusercontent.com/47950669/187898264-17c7b658-1bd8-476a-832f-17caf945b65e.png)

**Comment by Manuel-3** [comment]
Make sure to set your Figura target version to 0.1.0 in the settings. Older versions will only look for `model.bbmodel` or `player_model.bbmodel` specifically.

**Comment by HastagGuigui** [comment]
Thanks, I'll look into it, though I remember actually putting the figura version to 0.1.0
